version: '2'
services:
  db:
    build: ./backend
    restart: always
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - /var/lib/mysql
    environment:
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD={DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_ALLOW_EMPTY_PASSWORD='yes'
    env_file: ./.env
    networks:
      - php-app-network
  php:
    restart: always
    build: ./frontend
    ports:
      - "${PHP_PORT}:80"
    volumes:
      - ./frontend:/var/www/html
    env_file: ./.env
    links:
      - db
    networks:
      - php-app-network
networks:
  php-app-network:
    driver: bridge
