db:
  build: ./backend
  restart: always
  ports:
    - "${MYSQL_PORT}:3306"
  volumes:
    - /var/lib/mysql
  environment:
    - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    - MYSQL_USER=${DB_USERNAME}
    - MYSQL_PASSWORD=${DB_PASSWORD}
    - MYSQL_DATABASE=${DB_NAME}
  env_file: ./.env
php:
  build: ./frontend
  restart: always
  ports:
    - "${PHP_PORT}:80"
  volumes:
    - ./frontend:/var/www/html
  env_file: ./.env
  links:
    - db